language: php

php:
    - 5.3
    - 5.4
    - 5.5

before_script:
    - pecl install aop-beta
    - curl -s http://getcomposer.org/installer | php
    - COMPOSER_ROOT_VERSION=dev-master php composer.phar install --dev

script:
    - bin/atoum -d tests/units

notifications:
    email:
        - ci@verylastroom.com

matrix:
   allow_failures:
       # wait for https://github.com/AOP-PHP/AOP/pull/82 ...
       - php: 5.5
